name: Deploy static to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup PHP & Composer (jika Laravel memerlukan)
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --no-interaction

      # Setup Node.js untuk Vite build
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install npm dependencies & build
        run: |
          npm install
          npm run build

      # Upload folder hasil build ke artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
